using System.Collections.Generic;
using System.Dynamic;

namespace Pacman
{
    public class OriginalLayoutLevel : ILevel
    {
        private const int GridWidth = 19;
        private const int GridHeight = 21;

        private List<Coordinates> wallCoordinates = new List<Coordinates>()
        {
            new Coordinates(0, 0),
            new Coordinates(0, 1),
            new Coordinates(0, 2),
            new Coordinates(0, 3),
            new Coordinates(0, 4),
            new Coordinates(0, 5),
            new Coordinates(0, 6),
            new Coordinates(0, 7),
            new Coordinates(0, 8),
            new Coordinates(0, 9),
            new Coordinates(0, 10),
            new Coordinates(0, 11),
            new Coordinates(0, 12),
            new Coordinates(0, 13),
            new Coordinates(0, 14),
            new Coordinates(0, 15),
            new Coordinates(0, 16),
            new Coordinates(0, 17),
            new Coordinates(0, 18),
            new Coordinates(1, 0),
            new Coordinates(1, 9),
            new Coordinates(1, 18),
            new Coordinates(2, 0),
            new Coordinates(2, 2),
            new Coordinates(2, 3),
            new Coordinates(2, 5),
            new Coordinates(2, 6),
            new Coordinates(2, 7),
            new Coordinates(2, 9),
            new Coordinates(2, 11),
            new Coordinates(2, 12),
            new Coordinates(2, 13),
            new Coordinates(2, 15),
            new Coordinates(2, 16),
            new Coordinates(2, 18),
            new Coordinates(3, 0),
            new Coordinates(3, 18),
            new Coordinates(4, 0),
            new Coordinates(4, 2),
            new Coordinates(4, 3),
            new Coordinates(4, 5),
            new Coordinates(4, 7),
            new Coordinates(4, 8),
            new Coordinates(4, 9),
            new Coordinates(4, 10),
            new Coordinates(4, 11),
            new Coordinates(4, 13),
            new Coordinates(4, 15),
            new Coordinates(4, 16),
            new Coordinates(4, 18),
            new Coordinates(5, 0),
            new Coordinates(5, 5),
            new Coordinates(5, 9),
            new Coordinates(5, 13),
            new Coordinates(5, 18),
            new Coordinates(6, 0),
            new Coordinates(6, 1),
            new Coordinates(6, 2),
            new Coordinates(6, 3),
            new Coordinates(6, 5),
            new Coordinates(6, 6),
            new Coordinates(6, 7),
            new Coordinates(6, 9),
            new Coordinates(6, 11),
            new Coordinates(6, 12),
            new Coordinates(6, 13),
            new Coordinates(6, 15),
            new Coordinates(6, 16),
            new Coordinates(6, 17),
            new Coordinates(6, 18),
            new Coordinates(7, 2),
            new Coordinates(7, 4),
            new Coordinates(7, 14),
            new Coordinates(7, 16),
            new Coordinates(8, 0),
            new Coordinates(8, 1),
            new Coordinates(8, 2),
            new Coordinates(8, 3),
            new Coordinates(8, 5),
            new Coordinates(8, 7),
            new Coordinates(8, 8),
            new Coordinates(8, 9),
            new Coordinates(8, 10),
            new Coordinates(8, 11),
            new Coordinates(8, 13),
            new Coordinates(8, 15),
            new Coordinates(8, 16),
            new Coordinates(8, 17),
            new Coordinates(8, 18),
            new Coordinates(8, 0),
            new Coordinates(8, 0),
            new Coordinates(8, 0),
            new Coordinates(8, 0),
            new Coordinates(8, 0),
            new Coordinates(9, 7),
            new Coordinates(9, 11),
            new Coordinates(10, 0),
            new Coordinates(10, 1),
            new Coordinates(10, 2),
            new Coordinates(10, 3),
            new Coordinates(10, 5),
            new Coordinates(10, 7),
            new Coordinates(10, 8),
            new Coordinates(10, 9),
            new Coordinates(10, 10),
            new Coordinates(10, 11),
            new Coordinates(10, 13),
            new Coordinates(10, 15),
            new Coordinates(10, 16),
            new Coordinates(10, 17),
            new Coordinates(10, 18),
            new Coordinates(11, 2),
            new Coordinates(11, 4),
            new Coordinates(11, 14),
            new Coordinates(11, 16),
            new Coordinates(12, 0),
            new Coordinates(12, 1),
            new Coordinates(12, 2),
            new Coordinates(12, 3),
            new Coordinates(12, 5),
            new Coordinates(12, 7),
            new Coordinates(12, 8),
            new Coordinates(12, 9),
            new Coordinates(12, 10),
            new Coordinates(12, 11),
            new Coordinates(12, 13),
            new Coordinates(12, 15),
            new Coordinates(12, 16),
            new Coordinates(12, 17),
            new Coordinates(12, 18),
            new Coordinates(13, 0),
            new Coordinates(13, 9),
            new Coordinates(13, 18),
            new Coordinates(14, 0),
            new Coordinates(14, 2),
            new Coordinates(14, 3),
            new Coordinates(14, 5),
            new Coordinates(14, 6),
            new Coordinates(14, 7),
            new Coordinates(14, 9),
            new Coordinates(14, 11),
            new Coordinates(14, 12),
            new Coordinates(14, 13),
            new Coordinates(14, 15),
            new Coordinates(14, 16),
            new Coordinates(14, 18),
            new Coordinates(15, 0),
            new Coordinates(15, 3),
            new Coordinates(15, 15),
            new Coordinates(15, 18),
            new Coordinates(16, 0),
            new Coordinates(16, 18),
            new Coordinates(16, 0),
            new Coordinates(16, 1),
            new Coordinates(16, 3),
            new Coordinates(16, 5),
            new Coordinates(16, 7),
            new Coordinates(16, 8),
            new Coordinates(16, 9),
            new Coordinates(16, 10),
            new Coordinates(16, 11),
            new Coordinates(16, 13),
            new Coordinates(16, 15),
            new Coordinates(16, 17),
            new Coordinates(16, 18),
            new Coordinates(17, 0),
            new Coordinates(17, 5),
            new Coordinates(17, 9),
            new Coordinates(17, 13),
            new Coordinates(17, 18),
            new Coordinates(18, 1),
            new Coordinates(18, 8),
            new Coordinates(18, 10),
            new Coordinates(18, 18),
            new Coordinates(19, 0),
            new Coordinates(19, 18),
            new Coordinates(20, 0),
            new Coordinates(20, 1),
            new Coordinates(20, 2),
            new Coordinates(20, 3),
            new Coordinates(20, 4),
            new Coordinates(20, 5),
            new Coordinates(20, 6),
            new Coordinates(20, 7),
            new Coordinates(20, 8),
            new Coordinates(20, 9),
            new Coordinates(20, 10),
            new Coordinates(20, 11),
            new Coordinates(20, 12),
            new Coordinates(20, 13),
            new Coordinates(20, 14),
            new Coordinates(20, 15),
            new Coordinates(20, 16),
            new Coordinates(20, 17),
            new Coordinates(20, 18)
        };

        public List<Coordinates> blankSpacesCoordinates = new List<Coordinates>()
        {
            new Coordinates(7, 0),
            new Coordinates(7, 1),
            new Coordinates(7, 2),
            new Coordinates(7, 0),
            new Coordinates(7, 1),
            new Coordinates(7, 2),
            new Coordinates(11, 0),
            new Coordinates(11, 1),
            new Coordinates(11, 2),
            new Coordinates(11, 0),
            new Coordinates(11, 1),
            new Coordinates(11, 2)
        };

        public int GetGridWidth()
        {
            return GridWidth;
        }
        
        public int GetGridHeight()
        {
            return GridHeight;
        }

        public List<Coordinates> GetWallCoordinates()
        {
            return wallCoordinates;
        }
        
        public List<Coordinates> GetBlankSpacesCoordinates()
        {
            return blankSpacesCoordinates;
        }
    }
}